// Decompiled with JetBrains decompiler
// Type: Terraria.Initializers.AchievementInitializer
// Assembly: TerrariaServer, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null
// MVID: C2103E81-0935-4BEA-9E98-4159FC80C2BB
// Assembly location: F:\Steam\steamapps\common\Terraria\TerrariaServer.exe

using Terraria.Achievements;
using Terraria.GameContent.Achievements;
using Terraria.GameContent.UI.Chat;
using Terraria.Localization;

namespace Terraria.Initializers
{
  public class AchievementInitializer
  {
    public static void Load()
    {
      if (Main.netMode == 2)
        return;
      Achievement achievement1 = new Achievement("TIMBER");
      achievement1.AddCondition(ItemPickupCondition.Create((short) 9, (short) 619, (short) 2504, (short) 620, (short) 2503, (short) 2260, (short) 621, (short) 911, (short) 1729));
      Main.Achievements.Register(achievement1);
      Achievement achievement2 = new Achievement("NO_HOBO");
      achievement2.AddCondition((AchievementCondition) ProgressionEventCondition.Create(8));
      Main.Achievements.Register(achievement2);
      Achievement achievement3 = new Achievement("OBTAIN_HAMMER");
      achievement3.AddCondition(ItemPickupCondition.Create((short) 2775, (short) 2746, (short) 3505, (short) 654, (short) 3517, (short) 7, (short) 3493, (short) 2780, (short) 1513, (short) 2516, (short) 660, (short) 3481, (short) 657, (short) 922, (short) 3511, (short) 2785, (short) 3499, (short) 3487, (short) 196, (short) 367, (short) 104, (short) 797, (short) 2320, (short) 787, (short) 1234, (short) 1262, (short) 3465, (short) 204, (short) 217, (short) 1507, (short) 3524, (short) 3522, (short) 3525, (short) 3523, (short) 1305));
      Main.Achievements.Register(achievement3);
      Achievement achievement4 = new Achievement("OOO_SHINY");
      achievement4.AddCondition(TileDestroyedCondition.Create((ushort) 7, (ushort) 6, (ushort) 9, (ushort) 8, (ushort) 166, (ushort) 167, (ushort) 168, (ushort) 169, (ushort) 22, (ushort) 204, (ushort) 58, (ushort) 107, (ushort) 108, (ushort) 111, (ushort) 221, (ushort) 222, (ushort) 223, (ushort) 211));
      Main.Achievements.Register(achievement4);
      Achievement achievement5 = new Achievement("HEART_BREAKER");
      achievement5.AddCondition(TileDestroyedCondition.Create((ushort) 12));
      Main.Achievements.Register(achievement5);
      Achievement achievement6 = new Achievement("HEAVY_METAL");
      achievement6.AddCondition(ItemPickupCondition.Create((short) 35, (short) 716));
      Main.Achievements.Register(achievement6);
      Achievement achievement7 = new Achievement("I_AM_LOOT");
      achievement7.AddCondition(CustomFlagCondition.Create("Peek"));
      Main.Achievements.Register(achievement7);
      Achievement achievement8 = new Achievement("STAR_POWER");
      achievement8.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement8);
      Achievement achievement9 = new Achievement("HOLD_ON_TIGHT");
      achievement9.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement9);
      Achievement achievement10 = new Achievement("EYE_ON_YOU");
      achievement10.AddCondition(NPCKilledCondition.Create((short) 4));
      Main.Achievements.Register(achievement10);
      Achievement achievement11 = new Achievement("SMASHING_POPPET");
      achievement11.AddCondition((AchievementCondition) ProgressionEventCondition.Create(7));
      Main.Achievements.Register(achievement11);
      Achievement achievement12 = new Achievement("WORM_FODDER");
      achievement12.AddCondition(NPCKilledCondition.Create((short) 13, (short) 14, (short) 15));
      Main.Achievements.Register(achievement12);
      Achievement achievement13 = new Achievement("MASTERMIND");
      achievement13.AddCondition(NPCKilledCondition.Create((short) 266));
      Main.Achievements.Register(achievement13);
      Achievement achievement14 = new Achievement("WHERES_MY_HONEY");
      achievement14.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement14);
      Achievement achievement15 = new Achievement("STING_OPERATION");
      achievement15.AddCondition(NPCKilledCondition.Create((short) 222));
      Main.Achievements.Register(achievement15);
      Achievement achievement16 = new Achievement("BONED");
      achievement16.AddCondition(NPCKilledCondition.Create((short) 35));
      Main.Achievements.Register(achievement16);
      Achievement achievement17 = new Achievement("DUNGEON_HEIST");
      achievement17.AddCondition(ItemPickupCondition.Create((short) 327));
      achievement17.AddCondition((AchievementCondition) ProgressionEventCondition.Create(19));
      Main.Achievements.Register(achievement17);
      Achievement achievement18 = new Achievement("ITS_GETTING_HOT_IN_HERE");
      achievement18.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement18);
      Achievement achievement19 = new Achievement("MINER_FOR_FIRE");
      achievement19.AddCondition(ItemCraftCondition.Create((short) 122));
      Main.Achievements.Register(achievement19);
      Achievement achievement20 = new Achievement("STILL_HUNGRY");
      achievement20.AddCondition(NPCKilledCondition.Create((short) 113, (short) 114));
      Main.Achievements.Register(achievement20);
      Achievement achievement21 = new Achievement("ITS_HARD");
      achievement21.AddCondition((AchievementCondition) ProgressionEventCondition.Create(9));
      Main.Achievements.Register(achievement21);
      Achievement achievement22 = new Achievement("BEGONE_EVIL");
      achievement22.AddCondition((AchievementCondition) ProgressionEventCondition.Create(6));
      Main.Achievements.Register(achievement22);
      Achievement achievement23 = new Achievement("EXTRA_SHINY");
      achievement23.AddCondition(TileDestroyedCondition.Create((ushort) 107, (ushort) 108, (ushort) 111, (ushort) 221, (ushort) 222, (ushort) 223));
      Main.Achievements.Register(achievement23);
      Achievement achievement24 = new Achievement("HEAD_IN_THE_CLOUDS");
      achievement24.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement24);
      Achievement achievement25 = new Achievement("LIKE_A_BOSS");
      achievement25.AddCondition(ItemPickupCondition.Create((short) 1133, (short) 1331, (short) 1307, (short) 267, (short) 1293, (short) 557, (short) 544, (short) 556, (short) 560, (short) 43, (short) 70));
      Main.Achievements.Register(achievement25);
      Achievement achievement26 = new Achievement("BUCKETS_OF_BOLTS");
      achievement26.AddCondition(NPCKilledCondition.Create((short) 125, (short) 126));
      achievement26.AddConditions(NPCKilledCondition.CreateMany((short) sbyte.MaxValue, (short) 134));
      achievement26.UseConditionsCompletedTracker();
      Main.Achievements.Register(achievement26);
      Achievement achievement27 = new Achievement("DRAX_ATTAX");
      achievement27.AddCondition(ItemCraftCondition.Create((short) 579, (short) 990));
      Main.Achievements.Register(achievement27);
      Achievement achievement28 = new Achievement("PHOTOSYNTHESIS");
      achievement28.AddCondition(TileDestroyedCondition.Create((ushort) 211));
      Main.Achievements.Register(achievement28);
      Achievement achievement29 = new Achievement("GET_A_LIFE");
      achievement29.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement29);
      Achievement achievement30 = new Achievement("THE_GREAT_SOUTHERN_PLANTKILL");
      achievement30.AddCondition(NPCKilledCondition.Create((short) 262));
      Main.Achievements.Register(achievement30);
      Achievement achievement31 = new Achievement("TEMPLE_RAIDER");
      achievement31.AddCondition(TileDestroyedCondition.Create((ushort) 226));
      Main.Achievements.Register(achievement31);
      Achievement achievement32 = new Achievement("LIHZAHRDIAN_IDOL");
      achievement32.AddCondition(NPCKilledCondition.Create((short) 245));
      Main.Achievements.Register(achievement32);
      Achievement achievement33 = new Achievement("ROBBING_THE_GRAVE");
      achievement33.AddCondition(ItemPickupCondition.Create((short) 1513, (short) 938, (short) 963, (short) 977, (short) 1300, (short) 1254, (short) 1514, (short) 679, (short) 759, (short) 1446, (short) 1445, (short) 1444, (short) 1183, (short) 1266, (short) 671));
      Main.Achievements.Register(achievement33);
      Achievement achievement34 = new Achievement("BIG_BOOTY");
      achievement34.AddCondition((AchievementCondition) ProgressionEventCondition.Create(20));
      Main.Achievements.Register(achievement34);
      Achievement achievement35 = new Achievement("FISH_OUT_OF_WATER");
      achievement35.AddCondition(NPCKilledCondition.Create((short) 370));
      Main.Achievements.Register(achievement35);
      Achievement achievement36 = new Achievement("OBSESSIVE_DEVOTION");
      achievement36.AddCondition(NPCKilledCondition.Create((short) 439));
      Main.Achievements.Register(achievement36);
      Achievement achievement37 = new Achievement("STAR_DESTROYER");
      achievement37.AddConditions(NPCKilledCondition.CreateMany((short) 517, (short) 422, (short) 507, (short) 493));
      Main.Achievements.Register(achievement37);
      Achievement achievement38 = new Achievement("CHAMPION_OF_TERRARIA");
      achievement38.AddCondition(NPCKilledCondition.Create((short) 398));
      Main.Achievements.Register(achievement38);
      Achievement achievement39 = new Achievement("BLOODBATH");
      achievement39.AddCondition((AchievementCondition) ProgressionEventCondition.Create(5));
      Main.Achievements.Register(achievement39);
      Achievement achievement40 = new Achievement("SLIPPERY_SHINOBI");
      achievement40.AddCondition(NPCKilledCondition.Create((short) 50));
      Main.Achievements.Register(achievement40);
      Achievement achievement41 = new Achievement("GOBLIN_PUNTER");
      achievement41.AddCondition((AchievementCondition) ProgressionEventCondition.Create(10));
      Main.Achievements.Register(achievement41);
      Achievement achievement42 = new Achievement("WALK_THE_PLANK");
      achievement42.AddCondition((AchievementCondition) ProgressionEventCondition.Create(11));
      Main.Achievements.Register(achievement42);
      Achievement achievement43 = new Achievement("KILL_THE_SUN");
      achievement43.AddCondition((AchievementCondition) ProgressionEventCondition.Create(3));
      Main.Achievements.Register(achievement43);
      Achievement achievement44 = new Achievement("DO_YOU_WANT_TO_SLAY_A_SNOWMAN");
      achievement44.AddCondition((AchievementCondition) ProgressionEventCondition.Create(12));
      Main.Achievements.Register(achievement44);
      Achievement achievement45 = new Achievement("TIN_FOIL_HATTER");
      achievement45.AddCondition((AchievementCondition) ProgressionEventCondition.Create(13));
      Main.Achievements.Register(achievement45);
      Achievement achievement46 = new Achievement("BALEFUL_HARVEST");
      achievement46.AddCondition((AchievementCondition) ProgressionEventCondition.Create(15));
      Main.Achievements.Register(achievement46);
      Achievement achievement47 = new Achievement("ICE_SCREAM");
      achievement47.AddCondition((AchievementCondition) ProgressionEventCondition.Create(14));
      Main.Achievements.Register(achievement47);
      Achievement achievement48 = new Achievement("STICKY_SITUATION");
      achievement48.AddCondition((AchievementCondition) ProgressionEventCondition.Create(16));
      Main.Achievements.Register(achievement48);
      Achievement achievement49 = new Achievement("REAL_ESTATE_AGENT");
      achievement49.AddCondition((AchievementCondition) ProgressionEventCondition.Create(17));
      Main.Achievements.Register(achievement49);
      Achievement achievement50 = new Achievement("NOT_THE_BEES");
      achievement50.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement50);
      Achievement achievement51 = new Achievement("JEEPERS_CREEPERS");
      achievement51.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement51);
      Achievement achievement52 = new Achievement("FUNKYTOWN");
      achievement52.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement52);
      Achievement achievement53 = new Achievement("INTO_ORBIT");
      achievement53.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement53);
      Achievement achievement54 = new Achievement("ROCK_BOTTOM");
      achievement54.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement54);
      Achievement achievement55 = new Achievement("MECHA_MAYHEM");
      achievement55.AddCondition((AchievementCondition) ProgressionEventCondition.Create(21));
      Main.Achievements.Register(achievement55);
      Achievement achievement56 = new Achievement("GELATIN_WORLD_TOUR");
      achievement56.AddConditions(NPCKilledCondition.CreateMany((short) -5, (short) -6, (short) 1, (short) 81, (short) 71, (short) -3, (short) 147, (short) 138, (short) -10, (short) 50, (short) 59, (short) 16, (short) -7, (short) 244, (short) -8, (short) -1, (short) -2, (short) 184, (short) 204, (short) 225, (short) -9, (short) 141, (short) 183, (short) -4));
      achievement56.UseConditionsCompletedTracker();
      Main.Achievements.Register(achievement56);
      Achievement achievement57 = new Achievement("FASHION_STATEMENT");
      achievement57.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement57);
      Achievement achievement58 = new Achievement("VEHICULAR_MANSLAUGHTER");
      achievement58.AddCondition(CustomFlagCondition.Create("Hit"));
      Main.Achievements.Register(achievement58);
      Achievement achievement59 = new Achievement("BULLDOZER");
      achievement59.AddCondition(CustomIntCondition.Create("Pick", 10000));
      achievement59.UseTrackerFromCondition("Pick");
      Main.Achievements.Register(achievement59);
      Achievement achievement60 = new Achievement("THERE_ARE_SOME_WHO_CALL_HIM");
      achievement60.AddCondition(NPCKilledCondition.Create((short) 45));
      Main.Achievements.Register(achievement60);
      Achievement achievement61 = new Achievement("DECEIVER_OF_FOOLS");
      achievement61.AddCondition(NPCKilledCondition.Create((short) 196));
      Main.Achievements.Register(achievement61);
      Achievement achievement62 = new Achievement("SWORD_OF_THE_HERO");
      achievement62.AddCondition(ItemPickupCondition.Create((short) 757));
      Main.Achievements.Register(achievement62);
      Achievement achievement63 = new Achievement("LUCKY_BREAK");
      achievement63.AddCondition(CustomFlagCondition.Create("Hit"));
      Main.Achievements.Register(achievement63);
      Achievement achievement64 = new Achievement("THROWING_LINES");
      achievement64.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement64);
      Achievement achievement65 = new Achievement("DYE_HARD");
      achievement65.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement65);
      Achievement achievement66 = new Achievement("SICK_THROW");
      achievement66.AddCondition(ItemPickupCondition.Create((short) 3389));
      Main.Achievements.Register(achievement66);
      Achievement achievement67 = new Achievement("FREQUENT_FLYER");
      achievement67.AddCondition(CustomFloatCondition.Create("Pay", 10000f));
      achievement67.UseTrackerFromCondition("Pay");
      Main.Achievements.Register(achievement67);
      Achievement achievement68 = new Achievement("THE_CAVALRY");
      achievement68.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement68);
      Achievement achievement69 = new Achievement("COMPLETELY_AWESOME");
      achievement69.AddCondition(ItemPickupCondition.Create((short) 98));
      Main.Achievements.Register(achievement69);
      Achievement achievement70 = new Achievement("TIL_DEATH");
      achievement70.AddCondition(NPCKilledCondition.Create((short) 53));
      Main.Achievements.Register(achievement70);
      Achievement achievement71 = new Achievement("ARCHAEOLOGIST");
      achievement71.AddCondition(NPCKilledCondition.Create((short) 52));
      Main.Achievements.Register(achievement71);
      Achievement achievement72 = new Achievement("PRETTY_IN_PINK");
      achievement72.AddCondition(NPCKilledCondition.Create((short) -4));
      Main.Achievements.Register(achievement72);
      Achievement achievement73 = new Achievement("RAINBOWS_AND_UNICORNS");
      achievement73.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement73);
      Achievement achievement74 = new Achievement("YOU_AND_WHAT_ARMY");
      achievement74.AddCondition(CustomFlagCondition.Create("Spawn"));
      Main.Achievements.Register(achievement74);
      Achievement achievement75 = new Achievement("PRISMANCER");
      achievement75.AddCondition(ItemPickupCondition.Create((short) 495));
      Main.Achievements.Register(achievement75);
      Achievement achievement76 = new Achievement("IT_CAN_TALK");
      achievement76.AddCondition((AchievementCondition) ProgressionEventCondition.Create(18));
      Main.Achievements.Register(achievement76);
      Achievement achievement77 = new Achievement("WATCH_YOUR_STEP");
      achievement77.AddCondition(CustomFlagCondition.Create("Hit"));
      Main.Achievements.Register(achievement77);
      Achievement achievement78 = new Achievement("MARATHON_MEDALIST");
      achievement78.AddCondition(CustomFloatCondition.Create("Move", 1106688f));
      achievement78.UseTrackerFromCondition("Move");
      Main.Achievements.Register(achievement78);
      Achievement achievement79 = new Achievement("GLORIOUS_GOLDEN_POLE");
      achievement79.AddCondition(ItemPickupCondition.Create((short) 2294));
      Main.Achievements.Register(achievement79);
      Achievement achievement80 = new Achievement("SERVANT_IN_TRAINING");
      achievement80.AddCondition(CustomFlagCondition.Create("Finish"));
      Main.Achievements.Register(achievement80);
      Achievement achievement81 = new Achievement("GOOD_LITTLE_SLAVE");
      achievement81.AddCondition(CustomIntCondition.Create("Finish", 10));
      achievement81.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement81);
      Achievement achievement82 = new Achievement("TROUT_MONKEY");
      achievement82.AddCondition(CustomIntCondition.Create("Finish", 25));
      achievement82.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement82);
      Achievement achievement83 = new Achievement("FAST_AND_FISHIOUS");
      achievement83.AddCondition(CustomIntCondition.Create("Finish", 50));
      achievement83.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement83);
      Achievement achievement84 = new Achievement("SUPREME_HELPER_MINION");
      achievement84.AddCondition(CustomIntCondition.Create("Finish", 200));
      achievement84.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement84);
      Achievement achievement85 = new Achievement("TOPPED_OFF");
      achievement85.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement85);
      Achievement achievement86 = new Achievement("SLAYER_OF_WORLDS");
      achievement86.AddCondition(NPCKilledCondition.Create((short) 13, (short) 14, (short) 15));
      achievement86.AddCondition(NPCKilledCondition.Create((short) 113, (short) 114));
      achievement86.AddCondition(NPCKilledCondition.Create((short) 125, (short) 126));
      achievement86.AddConditions(NPCKilledCondition.CreateMany((short) 4, (short) 35, (short) 50, (short) 222, (short) 113, (short) 134, (short) sbyte.MaxValue, (short) 262, (short) 245, (short) 439, (short) 398, (short) 370));
      achievement86.UseConditionsCompletedTracker();
      Main.Achievements.Register(achievement86);
      Achievement achievement87 = new Achievement("YOU_CAN_DO_IT");
      achievement87.AddCondition((AchievementCondition) ProgressionEventCondition.Create(1));
      Main.Achievements.Register(achievement87);
      Achievement achievement88 = new Achievement("MATCHING_ATTIRE");
      achievement88.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement88);
      int num1 = 0;
      AchievementManager achievements1 = Main.Achievements;
      string achievementName1 = "TIMBER";
      int iconIndex1 = num1;
      int num2 = 1;
      int num3 = iconIndex1 + num2;
      achievements1.RegisterIconIndex(achievementName1, iconIndex1);
      AchievementManager achievements2 = Main.Achievements;
      string achievementName2 = "NO_HOBO";
      int iconIndex2 = num3;
      int num4 = 1;
      int num5 = iconIndex2 + num4;
      achievements2.RegisterIconIndex(achievementName2, iconIndex2);
      AchievementManager achievements3 = Main.Achievements;
      string achievementName3 = "OBTAIN_HAMMER";
      int iconIndex3 = num5;
      int num6 = 1;
      int num7 = iconIndex3 + num6;
      achievements3.RegisterIconIndex(achievementName3, iconIndex3);
      AchievementManager achievements4 = Main.Achievements;
      string achievementName4 = "HEART_BREAKER";
      int iconIndex4 = num7;
      int num8 = 1;
      int num9 = iconIndex4 + num8;
      achievements4.RegisterIconIndex(achievementName4, iconIndex4);
      AchievementManager achievements5 = Main.Achievements;
      string achievementName5 = "OOO_SHINY";
      int iconIndex5 = num9;
      int num10 = 1;
      int num11 = iconIndex5 + num10;
      achievements5.RegisterIconIndex(achievementName5, iconIndex5);
      AchievementManager achievements6 = Main.Achievements;
      string achievementName6 = "HEAVY_METAL";
      int iconIndex6 = num11;
      int num12 = 1;
      int num13 = iconIndex6 + num12;
      achievements6.RegisterIconIndex(achievementName6, iconIndex6);
      AchievementManager achievements7 = Main.Achievements;
      string achievementName7 = "I_AM_LOOT";
      int iconIndex7 = num13;
      int num14 = 1;
      int num15 = iconIndex7 + num14;
      achievements7.RegisterIconIndex(achievementName7, iconIndex7);
      AchievementManager achievements8 = Main.Achievements;
      string achievementName8 = "STAR_POWER";
      int iconIndex8 = num15;
      int num16 = 1;
      int num17 = iconIndex8 + num16;
      achievements8.RegisterIconIndex(achievementName8, iconIndex8);
      AchievementManager achievements9 = Main.Achievements;
      string achievementName9 = "HOLD_ON_TIGHT";
      int iconIndex9 = num17;
      int num18 = 1;
      int num19 = iconIndex9 + num18;
      achievements9.RegisterIconIndex(achievementName9, iconIndex9);
      AchievementManager achievements10 = Main.Achievements;
      string achievementName10 = "EYE_ON_YOU";
      int iconIndex10 = num19;
      int num20 = 1;
      int num21 = iconIndex10 + num20;
      achievements10.RegisterIconIndex(achievementName10, iconIndex10);
      AchievementManager achievements11 = Main.Achievements;
      string achievementName11 = "SMASHING_POPPET";
      int iconIndex11 = num21;
      int num22 = 1;
      int num23 = iconIndex11 + num22;
      achievements11.RegisterIconIndex(achievementName11, iconIndex11);
      AchievementManager achievements12 = Main.Achievements;
      string achievementName12 = "WORM_FODDER";
      int iconIndex12 = num23;
      int num24 = 1;
      int num25 = iconIndex12 + num24;
      achievements12.RegisterIconIndex(achievementName12, iconIndex12);
      AchievementManager achievements13 = Main.Achievements;
      string achievementName13 = "MASTERMIND";
      int iconIndex13 = num25;
      int num26 = 1;
      int num27 = iconIndex13 + num26;
      achievements13.RegisterIconIndex(achievementName13, iconIndex13);
      AchievementManager achievements14 = Main.Achievements;
      string achievementName14 = "WHERES_MY_HONEY";
      int iconIndex14 = num27;
      int num28 = 1;
      int num29 = iconIndex14 + num28;
      achievements14.RegisterIconIndex(achievementName14, iconIndex14);
      AchievementManager achievements15 = Main.Achievements;
      string achievementName15 = "STING_OPERATION";
      int iconIndex15 = num29;
      int num30 = 1;
      int num31 = iconIndex15 + num30;
      achievements15.RegisterIconIndex(achievementName15, iconIndex15);
      AchievementManager achievements16 = Main.Achievements;
      string achievementName16 = "BONED";
      int iconIndex16 = num31;
      int num32 = 1;
      int num33 = iconIndex16 + num32;
      achievements16.RegisterIconIndex(achievementName16, iconIndex16);
      AchievementManager achievements17 = Main.Achievements;
      string achievementName17 = "DUNGEON_HEIST";
      int iconIndex17 = num33;
      int num34 = 1;
      int num35 = iconIndex17 + num34;
      achievements17.RegisterIconIndex(achievementName17, iconIndex17);
      AchievementManager achievements18 = Main.Achievements;
      string achievementName18 = "ITS_GETTING_HOT_IN_HERE";
      int iconIndex18 = num35;
      int num36 = 1;
      int num37 = iconIndex18 + num36;
      achievements18.RegisterIconIndex(achievementName18, iconIndex18);
      AchievementManager achievements19 = Main.Achievements;
      string achievementName19 = "MINER_FOR_FIRE";
      int iconIndex19 = num37;
      int num38 = 1;
      int num39 = iconIndex19 + num38;
      achievements19.RegisterIconIndex(achievementName19, iconIndex19);
      AchievementManager achievements20 = Main.Achievements;
      string achievementName20 = "STILL_HUNGRY";
      int iconIndex20 = num39;
      int num40 = 1;
      int num41 = iconIndex20 + num40;
      achievements20.RegisterIconIndex(achievementName20, iconIndex20);
      AchievementManager achievements21 = Main.Achievements;
      string achievementName21 = "ITS_HARD";
      int iconIndex21 = num41;
      int num42 = 1;
      int num43 = iconIndex21 + num42;
      achievements21.RegisterIconIndex(achievementName21, iconIndex21);
      AchievementManager achievements22 = Main.Achievements;
      string achievementName22 = "BEGONE_EVIL";
      int iconIndex22 = num43;
      int num44 = 1;
      int num45 = iconIndex22 + num44;
      achievements22.RegisterIconIndex(achievementName22, iconIndex22);
      AchievementManager achievements23 = Main.Achievements;
      string achievementName23 = "EXTRA_SHINY";
      int iconIndex23 = num45;
      int num46 = 1;
      int num47 = iconIndex23 + num46;
      achievements23.RegisterIconIndex(achievementName23, iconIndex23);
      AchievementManager achievements24 = Main.Achievements;
      string achievementName24 = "HEAD_IN_THE_CLOUDS";
      int iconIndex24 = num47;
      int num48 = 1;
      int num49 = iconIndex24 + num48;
      achievements24.RegisterIconIndex(achievementName24, iconIndex24);
      AchievementManager achievements25 = Main.Achievements;
      string achievementName25 = "LIKE_A_BOSS";
      int iconIndex25 = num49;
      int num50 = 1;
      int num51 = iconIndex25 + num50;
      achievements25.RegisterIconIndex(achievementName25, iconIndex25);
      AchievementManager achievements26 = Main.Achievements;
      string achievementName26 = "BUCKETS_OF_BOLTS";
      int iconIndex26 = num51;
      int num52 = 1;
      int num53 = iconIndex26 + num52;
      achievements26.RegisterIconIndex(achievementName26, iconIndex26);
      AchievementManager achievements27 = Main.Achievements;
      string achievementName27 = "DRAX_ATTAX";
      int iconIndex27 = num53;
      int num54 = 1;
      int num55 = iconIndex27 + num54;
      achievements27.RegisterIconIndex(achievementName27, iconIndex27);
      AchievementManager achievements28 = Main.Achievements;
      string achievementName28 = "PHOTOSYNTHESIS";
      int iconIndex28 = num55;
      int num56 = 1;
      int num57 = iconIndex28 + num56;
      achievements28.RegisterIconIndex(achievementName28, iconIndex28);
      AchievementManager achievements29 = Main.Achievements;
      string achievementName29 = "GET_A_LIFE";
      int iconIndex29 = num57;
      int num58 = 1;
      int num59 = iconIndex29 + num58;
      achievements29.RegisterIconIndex(achievementName29, iconIndex29);
      AchievementManager achievements30 = Main.Achievements;
      string achievementName30 = "THE_GREAT_SOUTHERN_PLANTKILL";
      int iconIndex30 = num59;
      int num60 = 1;
      int num61 = iconIndex30 + num60;
      achievements30.RegisterIconIndex(achievementName30, iconIndex30);
      AchievementManager achievements31 = Main.Achievements;
      string achievementName31 = "TEMPLE_RAIDER";
      int iconIndex31 = num61;
      int num62 = 1;
      int num63 = iconIndex31 + num62;
      achievements31.RegisterIconIndex(achievementName31, iconIndex31);
      AchievementManager achievements32 = Main.Achievements;
      string achievementName32 = "LIHZAHRDIAN_IDOL";
      int iconIndex32 = num63;
      int num64 = 1;
      int num65 = iconIndex32 + num64;
      achievements32.RegisterIconIndex(achievementName32, iconIndex32);
      AchievementManager achievements33 = Main.Achievements;
      string achievementName33 = "ROBBING_THE_GRAVE";
      int iconIndex33 = num65;
      int num66 = 1;
      int num67 = iconIndex33 + num66;
      achievements33.RegisterIconIndex(achievementName33, iconIndex33);
      AchievementManager achievements34 = Main.Achievements;
      string achievementName34 = "BIG_BOOTY";
      int iconIndex34 = num67;
      int num68 = 1;
      int num69 = iconIndex34 + num68;
      achievements34.RegisterIconIndex(achievementName34, iconIndex34);
      AchievementManager achievements35 = Main.Achievements;
      string achievementName35 = "FISH_OUT_OF_WATER";
      int iconIndex35 = num69;
      int num70 = 1;
      int num71 = iconIndex35 + num70;
      achievements35.RegisterIconIndex(achievementName35, iconIndex35);
      AchievementManager achievements36 = Main.Achievements;
      string achievementName36 = "OBSESSIVE_DEVOTION";
      int iconIndex36 = num71;
      int num72 = 1;
      int num73 = iconIndex36 + num72;
      achievements36.RegisterIconIndex(achievementName36, iconIndex36);
      AchievementManager achievements37 = Main.Achievements;
      string achievementName37 = "STAR_DESTROYER";
      int iconIndex37 = num73;
      int num74 = 1;
      int num75 = iconIndex37 + num74;
      achievements37.RegisterIconIndex(achievementName37, iconIndex37);
      AchievementManager achievements38 = Main.Achievements;
      string achievementName38 = "CHAMPION_OF_TERRARIA";
      int iconIndex38 = num75;
      int num76 = 1;
      int num77 = iconIndex38 + num76;
      achievements38.RegisterIconIndex(achievementName38, iconIndex38);
      AchievementManager achievements39 = Main.Achievements;
      string achievementName39 = "BLOODBATH";
      int iconIndex39 = num77;
      int num78 = 1;
      int num79 = iconIndex39 + num78;
      achievements39.RegisterIconIndex(achievementName39, iconIndex39);
      AchievementManager achievements40 = Main.Achievements;
      string achievementName40 = "GOBLIN_PUNTER";
      int iconIndex40 = num79;
      int num80 = 1;
      int num81 = iconIndex40 + num80;
      achievements40.RegisterIconIndex(achievementName40, iconIndex40);
      AchievementManager achievements41 = Main.Achievements;
      string achievementName41 = "KILL_THE_SUN";
      int iconIndex41 = num81;
      int num82 = 1;
      int num83 = iconIndex41 + num82;
      achievements41.RegisterIconIndex(achievementName41, iconIndex41);
      AchievementManager achievements42 = Main.Achievements;
      string achievementName42 = "WALK_THE_PLANK";
      int iconIndex42 = num83;
      int num84 = 1;
      int num85 = iconIndex42 + num84;
      achievements42.RegisterIconIndex(achievementName42, iconIndex42);
      AchievementManager achievements43 = Main.Achievements;
      string achievementName43 = "DO_YOU_WANT_TO_SLAY_A_SNOWMAN";
      int iconIndex43 = num85;
      int num86 = 1;
      int num87 = iconIndex43 + num86;
      achievements43.RegisterIconIndex(achievementName43, iconIndex43);
      AchievementManager achievements44 = Main.Achievements;
      string achievementName44 = "TIN_FOIL_HATTER";
      int iconIndex44 = num87;
      int num88 = 1;
      int num89 = iconIndex44 + num88;
      achievements44.RegisterIconIndex(achievementName44, iconIndex44);
      AchievementManager achievements45 = Main.Achievements;
      string achievementName45 = "BALEFUL_HARVEST";
      int iconIndex45 = num89;
      int num90 = 1;
      int num91 = iconIndex45 + num90;
      achievements45.RegisterIconIndex(achievementName45, iconIndex45);
      AchievementManager achievements46 = Main.Achievements;
      string achievementName46 = "ICE_SCREAM";
      int iconIndex46 = num91;
      int num92 = 1;
      int num93 = iconIndex46 + num92;
      achievements46.RegisterIconIndex(achievementName46, iconIndex46);
      AchievementManager achievements47 = Main.Achievements;
      string achievementName47 = "SLIPPERY_SHINOBI";
      int iconIndex47 = num93;
      int num94 = 1;
      int num95 = iconIndex47 + num94;
      achievements47.RegisterIconIndex(achievementName47, iconIndex47);
      AchievementManager achievements48 = Main.Achievements;
      string achievementName48 = "STICKY_SITUATION";
      int iconIndex48 = num95;
      int num96 = 1;
      int num97 = iconIndex48 + num96;
      achievements48.RegisterIconIndex(achievementName48, iconIndex48);
      AchievementManager achievements49 = Main.Achievements;
      string achievementName49 = "REAL_ESTATE_AGENT";
      int iconIndex49 = num97;
      int num98 = 1;
      int num99 = iconIndex49 + num98;
      achievements49.RegisterIconIndex(achievementName49, iconIndex49);
      AchievementManager achievements50 = Main.Achievements;
      string achievementName50 = "NOT_THE_BEES";
      int iconIndex50 = num99;
      int num100 = 1;
      int num101 = iconIndex50 + num100;
      achievements50.RegisterIconIndex(achievementName50, iconIndex50);
      AchievementManager achievements51 = Main.Achievements;
      string achievementName51 = "JEEPERS_CREEPERS";
      int iconIndex51 = num101;
      int num102 = 1;
      int num103 = iconIndex51 + num102;
      achievements51.RegisterIconIndex(achievementName51, iconIndex51);
      AchievementManager achievements52 = Main.Achievements;
      string achievementName52 = "FUNKYTOWN";
      int iconIndex52 = num103;
      int num104 = 1;
      int num105 = iconIndex52 + num104;
      achievements52.RegisterIconIndex(achievementName52, iconIndex52);
      AchievementManager achievements53 = Main.Achievements;
      string achievementName53 = "INTO_ORBIT";
      int iconIndex53 = num105;
      int num106 = 1;
      int num107 = iconIndex53 + num106;
      achievements53.RegisterIconIndex(achievementName53, iconIndex53);
      AchievementManager achievements54 = Main.Achievements;
      string achievementName54 = "ROCK_BOTTOM";
      int iconIndex54 = num107;
      int num108 = 1;
      int num109 = iconIndex54 + num108;
      achievements54.RegisterIconIndex(achievementName54, iconIndex54);
      AchievementManager achievements55 = Main.Achievements;
      string achievementName55 = "MECHA_MAYHEM";
      int iconIndex55 = num109;
      int num110 = 1;
      int num111 = iconIndex55 + num110;
      achievements55.RegisterIconIndex(achievementName55, iconIndex55);
      AchievementManager achievements56 = Main.Achievements;
      string achievementName56 = "GELATIN_WORLD_TOUR";
      int iconIndex56 = num111;
      int num112 = 1;
      int num113 = iconIndex56 + num112;
      achievements56.RegisterIconIndex(achievementName56, iconIndex56);
      AchievementManager achievements57 = Main.Achievements;
      string achievementName57 = "FASHION_STATEMENT";
      int iconIndex57 = num113;
      int num114 = 1;
      int num115 = iconIndex57 + num114;
      achievements57.RegisterIconIndex(achievementName57, iconIndex57);
      AchievementManager achievements58 = Main.Achievements;
      string achievementName58 = "VEHICULAR_MANSLAUGHTER";
      int iconIndex58 = num115;
      int num116 = 1;
      int num117 = iconIndex58 + num116;
      achievements58.RegisterIconIndex(achievementName58, iconIndex58);
      AchievementManager achievements59 = Main.Achievements;
      string achievementName59 = "BULLDOZER";
      int iconIndex59 = num117;
      int num118 = 1;
      int num119 = iconIndex59 + num118;
      achievements59.RegisterIconIndex(achievementName59, iconIndex59);
      AchievementManager achievements60 = Main.Achievements;
      string achievementName60 = "THERE_ARE_SOME_WHO_CALL_HIM";
      int iconIndex60 = num119;
      int num120 = 1;
      int num121 = iconIndex60 + num120;
      achievements60.RegisterIconIndex(achievementName60, iconIndex60);
      AchievementManager achievements61 = Main.Achievements;
      string achievementName61 = "DECEIVER_OF_FOOLS";
      int iconIndex61 = num121;
      int num122 = 1;
      int num123 = iconIndex61 + num122;
      achievements61.RegisterIconIndex(achievementName61, iconIndex61);
      AchievementManager achievements62 = Main.Achievements;
      string achievementName62 = "SWORD_OF_THE_HERO";
      int iconIndex62 = num123;
      int num124 = 1;
      int num125 = iconIndex62 + num124;
      achievements62.RegisterIconIndex(achievementName62, iconIndex62);
      AchievementManager achievements63 = Main.Achievements;
      string achievementName63 = "LUCKY_BREAK";
      int iconIndex63 = num125;
      int num126 = 1;
      int num127 = iconIndex63 + num126;
      achievements63.RegisterIconIndex(achievementName63, iconIndex63);
      AchievementManager achievements64 = Main.Achievements;
      string achievementName64 = "THROWING_LINES";
      int iconIndex64 = num127;
      int num128 = 1;
      int num129 = iconIndex64 + num128;
      achievements64.RegisterIconIndex(achievementName64, iconIndex64);
      AchievementManager achievements65 = Main.Achievements;
      string achievementName65 = "DYE_HARD";
      int iconIndex65 = num129;
      int num130 = 1;
      int num131 = iconIndex65 + num130;
      achievements65.RegisterIconIndex(achievementName65, iconIndex65);
      AchievementManager achievements66 = Main.Achievements;
      string achievementName66 = "FREQUENT_FLYER";
      int iconIndex66 = num131;
      int num132 = 1;
      int num133 = iconIndex66 + num132;
      achievements66.RegisterIconIndex(achievementName66, iconIndex66);
      AchievementManager achievements67 = Main.Achievements;
      string achievementName67 = "THE_CAVALRY";
      int iconIndex67 = num133;
      int num134 = 1;
      int num135 = iconIndex67 + num134;
      achievements67.RegisterIconIndex(achievementName67, iconIndex67);
      AchievementManager achievements68 = Main.Achievements;
      string achievementName68 = "COMPLETELY_AWESOME";
      int iconIndex68 = num135;
      int num136 = 1;
      int num137 = iconIndex68 + num136;
      achievements68.RegisterIconIndex(achievementName68, iconIndex68);
      AchievementManager achievements69 = Main.Achievements;
      string achievementName69 = "TIL_DEATH";
      int iconIndex69 = num137;
      int num138 = 1;
      int num139 = iconIndex69 + num138;
      achievements69.RegisterIconIndex(achievementName69, iconIndex69);
      AchievementManager achievements70 = Main.Achievements;
      string achievementName70 = "ARCHAEOLOGIST";
      int iconIndex70 = num139;
      int num140 = 1;
      int num141 = iconIndex70 + num140;
      achievements70.RegisterIconIndex(achievementName70, iconIndex70);
      AchievementManager achievements71 = Main.Achievements;
      string achievementName71 = "PRETTY_IN_PINK";
      int iconIndex71 = num141;
      int num142 = 1;
      int num143 = iconIndex71 + num142;
      achievements71.RegisterIconIndex(achievementName71, iconIndex71);
      AchievementManager achievements72 = Main.Achievements;
      string achievementName72 = "RAINBOWS_AND_UNICORNS";
      int iconIndex72 = num143;
      int num144 = 1;
      int num145 = iconIndex72 + num144;
      achievements72.RegisterIconIndex(achievementName72, iconIndex72);
      AchievementManager achievements73 = Main.Achievements;
      string achievementName73 = "YOU_AND_WHAT_ARMY";
      int iconIndex73 = num145;
      int num146 = 1;
      int num147 = iconIndex73 + num146;
      achievements73.RegisterIconIndex(achievementName73, iconIndex73);
      AchievementManager achievements74 = Main.Achievements;
      string achievementName74 = "PRISMANCER";
      int iconIndex74 = num147;
      int num148 = 1;
      int num149 = iconIndex74 + num148;
      achievements74.RegisterIconIndex(achievementName74, iconIndex74);
      AchievementManager achievements75 = Main.Achievements;
      string achievementName75 = "IT_CAN_TALK";
      int iconIndex75 = num149;
      int num150 = 1;
      int num151 = iconIndex75 + num150;
      achievements75.RegisterIconIndex(achievementName75, iconIndex75);
      AchievementManager achievements76 = Main.Achievements;
      string achievementName76 = "WATCH_YOUR_STEP";
      int iconIndex76 = num151;
      int num152 = 1;
      int num153 = iconIndex76 + num152;
      achievements76.RegisterIconIndex(achievementName76, iconIndex76);
      AchievementManager achievements77 = Main.Achievements;
      string achievementName77 = "MARATHON_MEDALIST";
      int iconIndex77 = num153;
      int num154 = 1;
      int num155 = iconIndex77 + num154;
      achievements77.RegisterIconIndex(achievementName77, iconIndex77);
      AchievementManager achievements78 = Main.Achievements;
      string achievementName78 = "GLORIOUS_GOLDEN_POLE";
      int iconIndex78 = num155;
      int num156 = 1;
      int num157 = iconIndex78 + num156;
      achievements78.RegisterIconIndex(achievementName78, iconIndex78);
      AchievementManager achievements79 = Main.Achievements;
      string achievementName79 = "SERVANT_IN_TRAINING";
      int iconIndex79 = num157;
      int num158 = 1;
      int num159 = iconIndex79 + num158;
      achievements79.RegisterIconIndex(achievementName79, iconIndex79);
      AchievementManager achievements80 = Main.Achievements;
      string achievementName80 = "GOOD_LITTLE_SLAVE";
      int iconIndex80 = num159;
      int num160 = 1;
      int num161 = iconIndex80 + num160;
      achievements80.RegisterIconIndex(achievementName80, iconIndex80);
      AchievementManager achievements81 = Main.Achievements;
      string achievementName81 = "TROUT_MONKEY";
      int iconIndex81 = num161;
      int num162 = 1;
      int num163 = iconIndex81 + num162;
      achievements81.RegisterIconIndex(achievementName81, iconIndex81);
      AchievementManager achievements82 = Main.Achievements;
      string achievementName82 = "FAST_AND_FISHIOUS";
      int iconIndex82 = num163;
      int num164 = 1;
      int num165 = iconIndex82 + num164;
      achievements82.RegisterIconIndex(achievementName82, iconIndex82);
      AchievementManager achievements83 = Main.Achievements;
      string achievementName83 = "SUPREME_HELPER_MINION";
      int iconIndex83 = num165;
      int num166 = 1;
      int num167 = iconIndex83 + num166;
      achievements83.RegisterIconIndex(achievementName83, iconIndex83);
      AchievementManager achievements84 = Main.Achievements;
      string achievementName84 = "TOPPED_OFF";
      int iconIndex84 = num167;
      int num168 = 1;
      int num169 = iconIndex84 + num168;
      achievements84.RegisterIconIndex(achievementName84, iconIndex84);
      AchievementManager achievements85 = Main.Achievements;
      string achievementName85 = "SLAYER_OF_WORLDS";
      int iconIndex85 = num169;
      int num170 = 1;
      int num171 = iconIndex85 + num170;
      achievements85.RegisterIconIndex(achievementName85, iconIndex85);
      AchievementManager achievements86 = Main.Achievements;
      string achievementName86 = "YOU_CAN_DO_IT";
      int iconIndex86 = num171;
      int num172 = 1;
      int num173 = iconIndex86 + num172;
      achievements86.RegisterIconIndex(achievementName86, iconIndex86);
      AchievementManager achievements87 = Main.Achievements;
      string achievementName87 = "SICK_THROW";
      int iconIndex87 = num173;
      int num174 = 1;
      int num175 = iconIndex87 + num174;
      achievements87.RegisterIconIndex(achievementName87, iconIndex87);
      AchievementManager achievements88 = Main.Achievements;
      string achievementName88 = "MATCHING_ATTIRE";
      int iconIndex88 = num175;
      int num176 = 1;
      int num177 = iconIndex88 + num176;
      achievements88.RegisterIconIndex(achievementName88, iconIndex88);
      AchievementCategory category1 = AchievementCategory.Slayer;
      Main.Achievements.RegisterAchievementCategory("EYE_ON_YOU", category1);
      Main.Achievements.RegisterAchievementCategory("SLIPPERY_SHINOBI", category1);
      Main.Achievements.RegisterAchievementCategory("WORM_FODDER", category1);
      Main.Achievements.RegisterAchievementCategory("MASTERMIND", category1);
      Main.Achievements.RegisterAchievementCategory("STING_OPERATION", category1);
      Main.Achievements.RegisterAchievementCategory("BONED", category1);
      Main.Achievements.RegisterAchievementCategory("STILL_HUNGRY", category1);
      Main.Achievements.RegisterAchievementCategory("BUCKETS_OF_BOLTS", category1);
      Main.Achievements.RegisterAchievementCategory("THE_GREAT_SOUTHERN_PLANTKILL", category1);
      Main.Achievements.RegisterAchievementCategory("LIHZAHRDIAN_IDOL", category1);
      Main.Achievements.RegisterAchievementCategory("FISH_OUT_OF_WATER", category1);
      Main.Achievements.RegisterAchievementCategory("OBSESSIVE_DEVOTION", category1);
      Main.Achievements.RegisterAchievementCategory("STAR_DESTROYER", category1);
      Main.Achievements.RegisterAchievementCategory("CHAMPION_OF_TERRARIA", category1);
      Main.Achievements.RegisterAchievementCategory("GOBLIN_PUNTER", category1);
      Main.Achievements.RegisterAchievementCategory("DO_YOU_WANT_TO_SLAY_A_SNOWMAN", category1);
      Main.Achievements.RegisterAchievementCategory("WALK_THE_PLANK", category1);
      Main.Achievements.RegisterAchievementCategory("BALEFUL_HARVEST", category1);
      Main.Achievements.RegisterAchievementCategory("ICE_SCREAM", category1);
      Main.Achievements.RegisterAchievementCategory("TIN_FOIL_HATTER", category1);
      Main.Achievements.RegisterAchievementCategory("TIL_DEATH", category1);
      Main.Achievements.RegisterAchievementCategory("THERE_ARE_SOME_WHO_CALL_HIM", category1);
      Main.Achievements.RegisterAchievementCategory("ARCHAEOLOGIST", category1);
      Main.Achievements.RegisterAchievementCategory("PRETTY_IN_PINK", category1);
      Main.Achievements.RegisterAchievementCategory("DECEIVER_OF_FOOLS", category1);
      Main.Achievements.RegisterAchievementCategory("VEHICULAR_MANSLAUGHTER", category1);
      AchievementCategory category2 = AchievementCategory.Explorer;
      Main.Achievements.RegisterAchievementCategory("SMASHING_POPPET", category2);
      Main.Achievements.RegisterAchievementCategory("BEGONE_EVIL", category2);
      Main.Achievements.RegisterAchievementCategory("ITS_HARD", category2);
      Main.Achievements.RegisterAchievementCategory("FUNKYTOWN", category2);
      Main.Achievements.RegisterAchievementCategory("WATCH_YOUR_STEP", category2);
      Main.Achievements.RegisterAchievementCategory("YOU_CAN_DO_IT", category2);
      Main.Achievements.RegisterAchievementCategory("BLOODBATH", category2);
      Main.Achievements.RegisterAchievementCategory("KILL_THE_SUN", category2);
      Main.Achievements.RegisterAchievementCategory("STICKY_SITUATION", category2);
      Main.Achievements.RegisterAchievementCategory("NO_HOBO", category2);
      Main.Achievements.RegisterAchievementCategory("IT_CAN_TALK", category2);
      Main.Achievements.RegisterAchievementCategory("HEART_BREAKER", category2);
      Main.Achievements.RegisterAchievementCategory("I_AM_LOOT", category2);
      Main.Achievements.RegisterAchievementCategory("ROBBING_THE_GRAVE", category2);
      Main.Achievements.RegisterAchievementCategory("GET_A_LIFE", category2);
      Main.Achievements.RegisterAchievementCategory("JEEPERS_CREEPERS", category2);
      Main.Achievements.RegisterAchievementCategory("WHERES_MY_HONEY", category2);
      Main.Achievements.RegisterAchievementCategory("DUNGEON_HEIST", category2);
      Main.Achievements.RegisterAchievementCategory("BIG_BOOTY", category2);
      Main.Achievements.RegisterAchievementCategory("ITS_GETTING_HOT_IN_HERE", category2);
      Main.Achievements.RegisterAchievementCategory("INTO_ORBIT", category2);
      Main.Achievements.RegisterAchievementCategory("ROCK_BOTTOM", category2);
      Main.Achievements.RegisterAchievementCategory("OOO_SHINY", category2);
      Main.Achievements.RegisterAchievementCategory("EXTRA_SHINY", category2);
      Main.Achievements.RegisterAchievementCategory("PHOTOSYNTHESIS", category2);
      AchievementCategory category3 = AchievementCategory.Challenger;
      Main.Achievements.RegisterAchievementCategory("GELATIN_WORLD_TOUR", category3);
      Main.Achievements.RegisterAchievementCategory("SLAYER_OF_WORLDS", category3);
      Main.Achievements.RegisterAchievementCategory("REAL_ESTATE_AGENT", category3);
      Main.Achievements.RegisterAchievementCategory("YOU_AND_WHAT_ARMY", category3);
      Main.Achievements.RegisterAchievementCategory("TOPPED_OFF", category3);
      Main.Achievements.RegisterAchievementCategory("MECHA_MAYHEM", category3);
      Main.Achievements.RegisterAchievementCategory("BULLDOZER", category3);
      Main.Achievements.RegisterAchievementCategory("NOT_THE_BEES", category3);
      Main.Achievements.RegisterAchievementCategory("RAINBOWS_AND_UNICORNS", category3);
      Main.Achievements.RegisterAchievementCategory("THROWING_LINES", category3);
      Main.Achievements.RegisterAchievementCategory("FREQUENT_FLYER", category3);
      Main.Achievements.RegisterAchievementCategory("LUCKY_BREAK", category3);
      Main.Achievements.RegisterAchievementCategory("MARATHON_MEDALIST", category3);
      Main.Achievements.RegisterAchievementCategory("SERVANT_IN_TRAINING", category3);
      Main.Achievements.RegisterAchievementCategory("GOOD_LITTLE_SLAVE", category3);
      Main.Achievements.RegisterAchievementCategory("TROUT_MONKEY", category3);
      Main.Achievements.RegisterAchievementCategory("FAST_AND_FISHIOUS", category3);
      Main.Achievements.RegisterAchievementCategory("SUPREME_HELPER_MINION", category3);
      AchievementCategory category4 = AchievementCategory.Collector;
      Main.Achievements.RegisterAchievementCategory("OBTAIN_HAMMER", category4);
      Main.Achievements.RegisterAchievementCategory("HEAVY_METAL", category4);
      Main.Achievements.RegisterAchievementCategory("STAR_POWER", category4);
      Main.Achievements.RegisterAchievementCategory("MINER_FOR_FIRE", category4);
      Main.Achievements.RegisterAchievementCategory("HEAD_IN_THE_CLOUDS", category4);
      Main.Achievements.RegisterAchievementCategory("DRAX_ATTAX", category4);
      Main.Achievements.RegisterAchievementCategory("PRISMANCER", category4);
      Main.Achievements.RegisterAchievementCategory("SWORD_OF_THE_HERO", category4);
      Main.Achievements.RegisterAchievementCategory("HOLD_ON_TIGHT", category4);
      Main.Achievements.RegisterAchievementCategory("THE_CAVALRY", category4);
      Main.Achievements.RegisterAchievementCategory("DYE_HARD", category4);
      Main.Achievements.RegisterAchievementCategory("MATCHING_ATTIRE", category4);
      Main.Achievements.RegisterAchievementCategory("FASHION_STATEMENT", category4);
      Main.Achievements.RegisterAchievementCategory("COMPLETELY_AWESOME", category4);
      Main.Achievements.RegisterAchievementCategory("TIMBER", category4);
      Main.Achievements.RegisterAchievementCategory("SICK_THROW", category4);
      Main.Achievements.RegisterAchievementCategory("GLORIOUS_GOLDEN_POLE", category4);
      Main.Achievements.RegisterAchievementCategory("TEMPLE_RAIDER", category4);
      Main.Achievements.RegisterAchievementCategory("LIKE_A_BOSS", category4);
      Main.Achievements.Load();
      Main.Achievements.OnAchievementCompleted += new Achievement.AchievementCompleted(AchievementInitializer.OnAchievementCompleted);
      AchievementsHelper.Initialize();
    }

    private static void OnAchievementCompleted(Achievement achievement)
    {
      Main.NewText(Language.GetTextValue("Achievements.Completed", (object) AchievementTagHandler.GenerateTag(achievement)), byte.MaxValue, byte.MaxValue, byte.MaxValue, false);
    }
  }
}
